# Generated by Django 4.0.3 on 2022-05-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, default='default-avtar.png', null=True, upload_to='users/'),
        ),
    ]
