# Generated by Django 4.0.3 on 2022-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, default='media/default-avtar.png', null=True, upload_to='users/'),
        ),
    ]
