# Generated by Django 4.0.3 on 2022-05-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_user_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
