# Generated by Django 4.0.3 on 2022-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_food_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.CharField(default=True, max_length=90),
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
