# Generated by Django 4.0.3 on 2022-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_food_restaurants_food_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(unique=True, upload_to='media/'),
        ),
    ]
